version: '3.8'

services:
  app:
    build: .
    container_name: nodejs-app
    restart: always
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST_NAME=0.0.0.0
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=nodeuser
      - DB_PASSWORD=Ntd05#12
      - DB_NAME=nodejs_db
